# Generated by Django 3.2 on 2021-05-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_user_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_index',
        ),
        migrations.AddField(
            model_name='task',
            name='user_data',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
